const mongoose = require('mongoose');

const customerSchema = new mongoose.Schema({
  // Auto-generated by pre-save hook — never set required:true here
  customerId: {
    type: String,
    unique: true,
    sparse: true,
  },

  // Linked user account — set when admin approves a registration
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

  name:  { type: String, required: true, trim: true },
  email: { type: String, required: true, unique: true, lowercase: true },
  phone: { type: String, default: '' },

  address: {
    street:  String,
    city:    String,
    state:   String,
    pincode: String,
  },
  connectionType: {
    type: String,
    enum: ['Domestic', 'Commercial', 'Industrial', 'Agricultural'],
    default: 'Domestic',
  },
  connectionStatus: {
    type: String,
    enum: ['Active', 'Inactive', 'Suspended', 'Disconnected'],
    default: 'Active',
  },
  meterNumber:        { type: String, unique: true, sparse: true },
  sanctionedLoad:     { type: Number, default: 0 },
  connectionDate:     { type: Date, default: Date.now },
  securityDeposit:    { type: Number, default: 0 },
  outstandingBalance: { type: Number, default: 0 },
}, { timestamps: true });

// Auto-generate customerId before first save
customerSchema.pre('save', async function (next) {
  if (!this.customerId) {
    const count = await mongoose.model('Customer').countDocuments();
    this.customerId = `CUST${String(count + 1).padStart(5, '0')}`;
  }
  next();
});

module.exports = mongoose.model('Customer', customerSchema);